name: AI Notion Planner

on:
  schedule:
    - cron: '0 5,17 * * *'
  workflow_dispatch:

jobs:
  run-ai-planner:
    runs-on: ubuntu-latest
    env: 
      TZ: Europe/Minsk
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create context file securely
        run: echo "${{ secrets.MY_CONTEXT }}" > context.txt

      - name: Run Python script
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          AI_TOKEN: ${{ secrets.AI_TOKEN }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
          PARENT_ID: ${{ secrets.PARENT_ID }}
          CONTEXT_FILE: "context.txt"
        run: python main.py